---
# tasks file for pi-install
- name: Set IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
- name: Set default gateway to specified 
  community.general.nmcli:
    conn_name: "Wired connection 1"
    ifname: "{{ nmtui.inf }}"
    type: "{{ nmtui.type }}"
    ip4: "{{ nmtui.ip4 }}"
    gw4: "{{ nmtui.gw4 }}"
    dns4: "{{ nmtui.ip4 }}"
    state: present
- name: Make directories for compose files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/docker
    - /opt/dpidetector-node
    - /opt/docker/tg-bot
    - /opt/docker/tg-bot/video
    - /opt/docker/tg-bot/env
- name: Copy network compose file 
  ansible.builtin.template:
    src: sing_compose.yml.j2
    dest: /opt/docker/docker-compose.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Copy repost compose file 
  ansible.builtin.template:
    src: tg_compose.yml.j2
    dest: /opt/docker/tg-bot/docker-compose.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Copy config file for sing-box
  ansible.builtin.template:
    src: config.json.j2
    dest: /etc/sing-box/config.json
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Copy config file for tg-repost-bts
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/docker/tg-bot/env/.env
    owner: 1024
    group: 1012
    mode: u=rw,g=r,o=r
- name: Copy config file for tg-repost-bst
  ansible.builtin.template:
    src: .env_bst.j2
    dest: /opt/docker/tg-bot/env/.env_bloodstains
    owner: 1024
    group: 1012
    mode: u=rw,g=r,o=r
- name: Copy config file for tg-repost-wts
  ansible.builtin.template:
    src: .env_wts.j2
    dest: /opt/docker/tg-bot/env/.env_whatsthere
    owner: 1024
    group: 1012
    mode: u=rw,g=r,o=r
- name: Checkout DPIDetector
  ansible.builtin.git:
    repo: 'https://github.com/DPIdetector/dpidetector-node.git'
    dest: /opt/dpidetector-node
- name: Copy DPIDetector config
  ansible.builtin.template:
    src: user.conf.j2
    dest: /opt/dpidetector-node/user.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Start network services
  community.docker.docker_compose:
    project_src: "{{ item }}"
  register: output
  with_items:
    - /opt/docker
    - /opt/dpidetector
    - /opt/docker/tg-bot