---
# tasks file for pi-install
- name: Set IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
- name: Set default gateway to specified 
  community.general.nmcli:
    conn_name: "Wired connection 1"
    ifname: "{{ nmtui.inf }}"
    type: "{{ nmtui.type }}"
    ip4: "{{ nmtui.ip4 }}"
    gw4: "{{ nmtui.gw4 }}"
    dns4: "{{ nmtui.ip4 }}"
    state: present
- name: Make directories for compose files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/docker
- name: Copy compose file 
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/docker/docker-compose.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Copy config file for sing-box
  ansible.builtin.template:
    src: config.json.j2
    dest: /etc/sing-box/config.json
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- name: Start services
  community.docker.docker_compose:
    project_src: "{{ item }}"
  register: output
  with_items:
    - /opt/docker